spring:
  application:
    name: memi-logistics-backend
  profiles:
    active: dev
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME:}
    password: ${MAILTRAP_PASSWORD:}
    properties:
      mail:
        smtp:
        auth: true
        starttls:
          enable: true
application:
  security:
    jwt:
      headers:
        refresh: Refresh-Token
        bearer-prefix: Bearer
    password-reset-url: ${PASSWORD_RESET_URL}:http://localhost:3000/reset-password
    password-reset-expiration: ${PASSWORD_RESET_EXPIRATION}:3600000 # 1 hour
