spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 900000 # 15 minutes for security in prod
    refresh-token-expiration: 604800000 # 7 days
    initial-admin:
      email: ${INITIAL_ADMIN_EMAIL:halefomhailu@memitrading.com}
      password: ${INITIAL_ADMIN_PASSWORD:Admin@123}
server:
  port: ${PORT:8080}